"""
PEK Lite – FastAPI Application Entry Point
Stable ASGI app for Railway deployment
"""

from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel
from typing import List, Optional

from PersonalityEngine_Kernel.engines.inference.inference_engine import run_inference


# -----------------------------
# FASTAPI APP (THIS IS WHAT RAILWAY NEEDS)
# -----------------------------
app = FastAPI(
    title="PEK Lite",
    version="1.0.0"
)


# -----------------------------
# REQUEST MODEL
# -----------------------------
class InferenceRequest(BaseModel):
    responses: List[str]
    context_flags: Optional[dict] = None
    forced_overrides: Optional[dict] = None


# -----------------------------
# HEALTH CHECK
# -----------------------------
@app.get("/health")
def health():
    return {
        "status": "ok",
        "engine": "PEK Lite"
    }


# -----------------------------
# INPUT NORMALIZATION
# -----------------------------
def build_engine_input(payload: InferenceRequest) -> dict:
    combined_statement = " ".join(payload.responses)

    return {
        "example_statement": combined_statement,
        "context_flags": payload.context_flags or {},
        "forced_overrides": payload.forced_overrides or {}
    }


# -----------------------------
# JSON INFERENCE ENDPOINT
# -----------------------------
@app.post("/infer")
def infer(payload: InferenceRequest):
    if not payload.responses:
        raise HTTPException(status_code=400, detail="No responses provided")

    engine_input = build_engine_input(payload)
    result = run_inference(engine_input)

    return JSONResponse(content=result)


# -----------------------------
# HTML REPORT ENDPOINT
# -----------------------------
@app.post("/report", response_class=HTMLResponse)
def render_report(payload: InferenceRequest):
    if not payload.responses:
        raise HTTPException(status_code=400, detail="No responses provided")

    engine_input = build_engine_input(payload)
    result = run_inference(engine_input)

    html = f"""
    <html>
    <head>
        <title>Personality Engine Kernel — Lite Snapshot</title>
        <style>
            body {{
                font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
                background: #0e0e11;
                color: #eaeaf0;
                padding: 60px 20px;
            }}
            .container {{
                max-width: 860px;
                margin: auto;
                background: #16161c;
                padding: 48px;
                border-radius: 14px;
                box-shadow: 0 20px 60px rgba(0,0,0,0.6);
            }}
            h1 {{
                font-size: 2.2em;
                margin-bottom: 6px;
            }}
            .sub {{
                color: #9aa0b0;
                margin-bottom: 32px;
            }}
            h2 {{
                margin-top: 36px;
                border-bottom: 1px solid #2a2a35;
                padding-bottom: 6px;
            }}
            ul {{
                line-height: 1.7;
            }}
            .footer {{
                margin-top: 40px;
                color: #777;
                font-size: 0.85em;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Personality Engine Kernel — Lite</h1>
            <div class="sub">Behavioral & cognitive pattern snapshot</div>

            <h2>Orientation Snapshot</h2>
            <p>{result["lite_translation"]["orientation_snapshot"]}</p>

            <h2>Real-World Signals</h2>
            <ul>
                {''.join(f"<li>{s}</li>" for s in result["lite_translation"]["real_world_signals"])}
            </ul>

            <h2>Strengths</h2>
            <ul>
                {''.join(f"<li>{s}</li>" for s in result["lite_translation"]["strengths"])}
            </ul>

            <h2>Common Misinterpretations</h2>
            <ul>
                {''.join(f"<li>{s}</li>" for s in result["lite_translation"]["common_misinterpretations"])}
            </ul>

            <h2>Reflection Prompts</h2>
            <ul>
                {''.join(f"<li>{s}</li>" for s in result["lite_translation"]["reflection_prompts"])}
            </ul>

            <div class="footer">
                Generated by PEK Lite
            </div>
        </div>
    </body>
    </html>
    """

    return HTMLResponse(content=html)
