"""
PEK Lite – FastAPI Application Entry Point
Thin HTTP wrapper around the Personality Engine Kernel.
"""

from fastapi import FastAPI, HTTPException
from fastapi.responses import HTMLResponse, JSONResponse
from pydantic import BaseModel

from PersonalityEngine_Kernel.engines.inference.inference_engine import run_inference


app = FastAPI(
    title="PEK Lite",
    version="0.4"
)


class InferenceRequest(BaseModel):
    responses: list[str]
    context_flags: dict | None = None
    forced_overrides: dict | None = None


@app.get("/health")
def health():
    return {
        "status": "ok",
        "engine": "PEK Lite"
    }


def render_lite_html(lite: dict) -> str:
    def li(items):
        return "".join(f"<li>{item}</li>" for item in items)

    orientation = lite.get("orientation_snapshot", "")
    real_world = lite.get("real_world_signals", []) or []
    strengths = lite.get("strengths", []) or []
    misinterp = lite.get("common_misinterpretations", []) or []
    prompts = lite.get("reflection_prompts", []) or []

    return f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>PEK Lite — Personality Snapshot</title>
        <style>
            body {{
                font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
                background: #0e0e11;
                color: #eaeaf0;
                padding: 60px 20px;
            }}
            .container {{
                max-width: 860px;
                margin: auto;
                background: #16161c;
                padding: 46px;
                border-radius: 14px;
                box-shadow: 0 20px 60px rgba(0,0,0,0.6);
            }}
            h1 {{
                font-size: 2.1em;
                margin: 0 0 6px 0;
            }}
            .sub {{
                color: #9a9ab0;
                margin-bottom: 28px;
            }}
            h2 {{
                margin-top: 28px;
                font-size: 1.15em;
                border-bottom: 1px solid #2a2a35;
                padding-bottom: 8px;
            }}
            p {{
                line-height: 1.6;
            }}
            ul {{
                line-height: 1.7;
                padding-left: 20px;
                margin: 12px 0 0 0;
            }}
            li {{
                margin-bottom: 8px;
            }}
            .footer {{
                margin-top: 34px;
                font-size: 0.85em;
                color: #777;
                text-align: center;
            }}
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Personality Engine Kernel — Lite</h1>
            <div class="sub">Behavioral & cognitive pattern snapshot</div>

            <h2>Orientation Snapshot</h2>
            <p>{orientation}</p>

            <h2>Real-World Signals</h2>
            <ul>{li(real_world) if real_world else "<li>No strong signals detected yet.</li>"}</ul>

            <h2>Strengths</h2>
            <ul>{li(strengths) if strengths else "<li>Not enough signal density to summarize strengths yet.</li>"}</ul>

            <h2>Common Misinterpretations</h2>
            <ul>{li(misinterp) if misinterp else "<li>No common misinterpretations detected yet.</li>"}</ul>

            <h2>Reflection Prompts</h2>
            <ul>{li(prompts) if prompts else "<li>Try adding 6–10 responses for a sharper read.</li>"}</ul>

            <div class="footer">
                Generated by PEK Lite · Full PEK available soon
            </div>
        </div>
    </body>
    </html>
    """


@app.post("/infer")
def infer(payload: InferenceRequest):
    if not payload.responses:
        raise HTTPException(status_code=400, detail="No responses provided")

    result = run_inference(
        responses=payload.responses,
        context_flags=payload.context_flags or {},
        forced_overrides=payload.forced_overrides or {}
    )

    return JSONResponse(result)


@app.post("/report", response_class=HTMLResponse)
def report(payload: InferenceRequest):
    if not payload.responses:
        raise HTTPException(status_code=400, detail="No responses provided")

    result = run_inference(
        responses=payload.responses,
        context_flags=payload.context_flags or {},
        forced_overrides=payload.forced_overrides or {}
    )

    lite = result.get("lite_translation", {}) or {}
    html = render_lite_html(lite)
    return HTMLResponse(content=html)
